### ISSUE TITLE
http-server: command not found

### ISSUE THREAD

**Issue by digzmo** [jadjoubran/web-starter-vanilla#7]
`npm install http-server`
`npm audit fix --force`

**Comment by jadjoubran** [comment]
Hey @digzmo 
Did you run `npm install` after cloning the repo? `http-server` is already in the dependencies

**Comment by digzmo** [comment]
It was odd because I already had current version of npm installed but oddly there were some issues/errors until I installed it separately.

**Comment by digzmo** [comment]
And yes I had run npm install

**Comment by jadjoubran** [comment]
Yeah weird.. I'll keep an eye on it if it happens again, but remember that I recommend using [Vite](https://vitejs.dev/) nowadays!
